%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.5

-ifndef(gtfs_realtime_pb).
-define(gtfs_realtime_pb, true).

-define(gtfs_realtime_pb_gpb_version, "3.26.5").

-ifndef('POSITION_PB_H').
-define('POSITION_PB_H', true).
-record('Position',
        {latitude               :: float() | integer() | infinity | '-infinity' | nan, % = 1
         longitude              :: float() | integer() | infinity | '-infinity' | nan, % = 2
         bearing                :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 3
         odometer               :: float() | integer() | infinity | '-infinity' | nan | undefined, % = 4
         speed                  :: float() | integer() | infinity | '-infinity' | nan | undefined % = 5
        }).
-endif.

-ifndef('VEHICLEDESCRIPTOR_PB_H').
-define('VEHICLEDESCRIPTOR_PB_H', true).
-record('VehicleDescriptor',
        {id                     :: binary() | iolist() | undefined, % = 1
         label                  :: binary() | iolist() | undefined, % = 2
         license_plate          :: binary() | iolist() | undefined % = 3
        }).
-endif.

-ifndef('TRIPDESCRIPTOR_PB_H').
-define('TRIPDESCRIPTOR_PB_H', true).
-record('TripDescriptor',
        {trip_id                :: binary() | iolist() | undefined, % = 1
         route_id               :: binary() | iolist() | undefined, % = 5
         direction_id           :: non_neg_integer() | undefined, % = 6, 32 bits
         start_time             :: binary() | iolist() | undefined, % = 2
         start_date             :: binary() | iolist() | undefined, % = 3
         schedule_relationship  :: 'SCHEDULED' | 'ADDED' | 'UNSCHEDULED' | 'CANCELED' | integer() | undefined % = 4, enum TripDescriptor.ScheduleRelationship
        }).
-endif.

-ifndef('VEHICLEPOSITION_PB_H').
-define('VEHICLEPOSITION_PB_H', true).
-record('VehiclePosition',
        {trip                   :: #'TripDescriptor'{} | undefined, % = 1
         vehicle                :: #'VehicleDescriptor'{} | undefined, % = 8
         position               :: #'Position'{} | undefined, % = 2
         current_stop_sequence  :: non_neg_integer() | undefined, % = 3, 32 bits
         stop_id                :: binary() | iolist() | undefined, % = 7
         current_status = 'IN_TRANSIT_TO' :: 'INCOMING_AT' | 'STOPPED_AT' | 'IN_TRANSIT_TO' | integer() | undefined, % = 4, enum VehiclePosition.VehicleStopStatus
         timestamp              :: non_neg_integer() | undefined, % = 5, 32 bits
         congestion_level       :: 'UNKNOWN_CONGESTION_LEVEL' | 'RUNNING_SMOOTHLY' | 'STOP_AND_GO' | 'CONGESTION' | 'SEVERE_CONGESTION' | integer() | undefined, % = 6, enum VehiclePosition.CongestionLevel
         occupancy_status       :: 'EMPTY' | 'MANY_SEATS_AVAILABLE' | 'FEW_SEATS_AVAILABLE' | 'STANDING_ROOM_ONLY' | 'CRUSHED_STANDING_ROOM_ONLY' | 'FULL' | 'NOT_ACCEPTING_PASSENGERS' | integer() | undefined % = 9, enum VehiclePosition.OccupancyStatus
        }).
-endif.

-ifndef('TRANSLATEDSTRING.TRANSLATION_PB_H').
-define('TRANSLATEDSTRING.TRANSLATION_PB_H', true).
-record('TranslatedString.Translation',
        {text                   :: binary() | iolist(), % = 1
         language               :: binary() | iolist() | undefined % = 2
        }).
-endif.

-ifndef('TRANSLATEDSTRING_PB_H').
-define('TRANSLATEDSTRING_PB_H', true).
-record('TranslatedString',
        {translation = []       :: [#'TranslatedString.Translation'{}] % = 1
        }).
-endif.

-ifndef('FEEDHEADER_PB_H').
-define('FEEDHEADER_PB_H', true).
-record('FeedHeader',
        {gtfs_realtime_version  :: binary() | iolist(), % = 1
         incrementality = 'FULL_DATASET' :: 'FULL_DATASET' | 'DIFFERENTIAL' | integer() | undefined, % = 2, enum FeedHeader.Incrementality
         timestamp              :: non_neg_integer() | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('ENTITYSELECTOR_PB_H').
-define('ENTITYSELECTOR_PB_H', true).
-record('EntitySelector',
        {agency_id              :: binary() | iolist() | undefined, % = 1
         route_id               :: binary() | iolist() | undefined, % = 2
         route_type             :: integer() | undefined, % = 3, 32 bits
         trip                   :: #'TripDescriptor'{} | undefined, % = 4
         stop_id                :: binary() | iolist() | undefined % = 5
        }).
-endif.

-ifndef('TRIPUPDATE.STOPTIMEEVENT_PB_H').
-define('TRIPUPDATE.STOPTIMEEVENT_PB_H', true).
-record('TripUpdate.StopTimeEvent',
        {delay                  :: integer() | undefined, % = 1, 32 bits
         time                   :: integer() | undefined, % = 2, 32 bits
         uncertainty            :: integer() | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('TRIPUPDATE.STOPTIMEUPDATE_PB_H').
-define('TRIPUPDATE.STOPTIMEUPDATE_PB_H', true).
-record('TripUpdate.StopTimeUpdate',
        {stop_sequence          :: non_neg_integer() | undefined, % = 1, 32 bits
         stop_id                :: binary() | iolist() | undefined, % = 4
         arrival                :: #'TripUpdate.StopTimeEvent'{} | undefined, % = 2
         departure              :: #'TripUpdate.StopTimeEvent'{} | undefined, % = 3
         schedule_relationship = 'SCHEDULED' :: 'SCHEDULED' | 'SKIPPED' | 'NO_DATA' | integer() | undefined % = 5, enum TripUpdate.StopTimeUpdate.ScheduleRelationship
        }).
-endif.

-ifndef('TRIPUPDATE_PB_H').
-define('TRIPUPDATE_PB_H', true).
-record('TripUpdate',
        {trip                   :: #'TripDescriptor'{}, % = 1
         vehicle                :: #'VehicleDescriptor'{} | undefined, % = 3
         stop_time_update = []  :: [#'TripUpdate.StopTimeUpdate'{}], % = 2
         timestamp              :: non_neg_integer() | undefined, % = 4, 32 bits
         delay                  :: integer() | undefined % = 5, 32 bits
        }).
-endif.

-ifndef('TIMERANGE_PB_H').
-define('TIMERANGE_PB_H', true).
-record('TimeRange',
        {start                  :: non_neg_integer() | undefined, % = 1, 32 bits
         'end'                  :: non_neg_integer() | undefined % = 2, 32 bits
        }).
-endif.

-ifndef('ALERT_PB_H').
-define('ALERT_PB_H', true).
-record('Alert',
        {active_period = []     :: [#'TimeRange'{}], % = 1
         informed_entity = []   :: [#'EntitySelector'{}], % = 5
         cause = 'UNKNOWN_CAUSE' :: 'UNKNOWN_CAUSE' | 'OTHER_CAUSE' | 'TECHNICAL_PROBLEM' | 'STRIKE' | 'DEMONSTRATION' | 'ACCIDENT' | 'HOLIDAY' | 'WEATHER' | 'MAINTENANCE' | 'CONSTRUCTION' | 'POLICE_ACTIVITY' | 'MEDICAL_EMERGENCY' | integer() | undefined, % = 6, enum Alert.Cause
         effect = 'UNKNOWN_EFFECT' :: 'NO_SERVICE' | 'REDUCED_SERVICE' | 'SIGNIFICANT_DELAYS' | 'DETOUR' | 'ADDITIONAL_SERVICE' | 'MODIFIED_SERVICE' | 'OTHER_EFFECT' | 'UNKNOWN_EFFECT' | 'STOP_MOVED' | integer() | undefined, % = 7, enum Alert.Effect
         url                    :: #'TranslatedString'{} | undefined, % = 8
         header_text            :: #'TranslatedString'{} | undefined, % = 10
         description_text       :: #'TranslatedString'{} | undefined % = 11
        }).
-endif.

-ifndef('FEEDENTITY_PB_H').
-define('FEEDENTITY_PB_H', true).
-record('FeedEntity',
        {id                     :: binary() | iolist(), % = 1
         is_deleted = false     :: boolean() | 0 | 1 | undefined, % = 2
         trip_update            :: #'TripUpdate'{} | undefined, % = 3
         vehicle                :: #'VehiclePosition'{} | undefined, % = 4
         alert                  :: #'Alert'{} | undefined % = 5
        }).
-endif.

-ifndef('FEEDMESSAGE_PB_H').
-define('FEEDMESSAGE_PB_H', true).
-record('FeedMessage',
        {header                 :: #'FeedHeader'{}, % = 1
         entity = []            :: [#'FeedEntity'{}] % = 2
        }).
-endif.

-endif.
